services:
  app:
    build:
      context: ..
      dockerfile: laravel-app/Dockerfile
    volumes:
      - appdata:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=tinder_app
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable
    ports:
      - "8082:80"
    volumes:
      - appdata:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tinder_app
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  scheduler:
    build:
      context: ..
      dockerfile: laravel-app/Dockerfile
    command: sh -c "while true; do php /var/www/html/artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - appdata:/var/www/html
    depends_on:
      - db

volumes:
  db_data: {}
  appdata: {}
